-- =========================================================================
-- TEACHERS TABLE UPGRADE & SEED FOR YAQEEN INSTITUTE
-- Run this in your Supabase SQL Editor if you want to sync all 9 teachers
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    avatar_url TEXT,
    languages TEXT NOT NULL,
    experience TEXT NOT NULL,
    specialization TEXT NOT NULL,
    education TEXT,
    bio TEXT,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure all columns exist
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS education TEXT;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS order_index INT DEFAULT 0;

-- Enable RLS & Policies
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public teachers select" ON public.teachers;
CREATE POLICY "Allow public teachers select" ON public.teachers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin teachers operations" ON public.teachers;
CREATE POLICY "Allow admin teachers operations" ON public.teachers FOR ALL USING (true);

-- Upsert / Insert the 9 standard teachers with rich details
INSERT INTO public.teachers (id, name, title, avatar_url, languages, experience, specialization, education, bio, order_index)
VALUES
(
  1,
  'Ustadh Mazin Yasir',
  'Senior Quran & Tajweed Specialist',
  '/images/teacher_mazin.jpg',
  'Arabic, English',
  '3+ Years',
  'Qur''an, Tajweed, Islamic Studies',
  'Degree in Islamic Studies & Quranic Sciences • Ijazah in Hafs ''an ''Asim',
  'Ustadh Mazin is an enthusiastic and supportive teacher who specializes in guiding beginner and intermediate students through Quran recitation with proper Makharij (articulation points) and Tajweed rules. His interactive approach helps children and adults develop confidence and a deep spiritual connection with the Holy Quran.',
  1
),
(
  2,
  'Ustadha Naira Tarek',
  'Arabic Language & Quran Instructor',
  '/images/teacher_naira.jpg',
  'Arabic, English',
  '4+ Years',
  'Qur''an, Arabic Language, Islamic Studies',
  'Bachelor of Arts in Arabic Linguistics & Classical Quranic Grammar',
  'Ustadha Naira has trained hundreds of young learners and female students worldwide. She blends classical Arabic grammar with engaging conversational practice and gentle Tajweed correction, creating an encouraging environment where students flourish.',
  2
),
(
  3,
  'Ustadh Mohammed Sabry',
  'Azhari Scholar & Hifz Coach',
  '/images/teacher_sabry.jpg',
  'Arabic, English',
  '4+ Years',
  'Tajweed, Hifz, Arabic Language, Fiqh, Seerah',
  'Graduate of Al-Azhar University (Faculty of Usul al-Din) • Certified Hafiz',
  'Ustadh Mohammed Sabry has memorized the entire Quran with multiple Ijazat. He specializes in intensive Hifz (memorization) coaching, Quranic Tafseer, and foundational Fiqh. His methodical revision strategies help students retain their memorization effortlessly.',
  3
),
(
  4,
  'Ustadha Amir Attaf',
  'Senior Tafseer & Islamic Studies Teacher',
  '/images/teacher_amira.jpg',
  'Arabic, English',
  '10+ Years',
  'Qur''an, Tajweed, Tafseer, Islamic Studies',
  'Master''s in Islamic Studies • Certified Tajweed Educator',
  'With over a decade of teaching experience across the UK and Middle East, Ustadha Amir is renowned for her profound knowledge of Quranic Tafseer and spiritual development. She tailors every class to each student''s individual pace, ensuring both intellectual clarity and heart-centered learning.',
  4
),
(
  5,
  'Ustadh Rahman Ali',
  'Lead Recitation & Makharij Coach',
  '/images/teacher_rahman.png',
  'Arabic, English, Urdu',
  '8+ Years',
  'Qur''an, Tajweed, Noorani Qaida',
  'Certified Qari • Ijazah in Ten Minor Qira''at',
  'Ustadh Rahman specializes in foundational Noorani Qaida for young beginners and advanced Tajweed melody and rhythm for older students. His patient demeanor makes learning smooth and enjoyable for all age groups.',
  5
),
(
  6,
  'Ustadha Aisha Khan',
  'Hadith & Islamic Manners Instructor',
  '/images/teacher_aisha.png',
  'Arabic, English',
  '6+ Years',
  'Tafseer, Hadith, Akhlaaq',
  'Alimiyyah Degree in Islamic Theology and Hadith Studies',
  'Ustadha Aisha focuses on bringing the prophetic traditions (Sunnah) to life for modern Muslim families. She guides students in understanding daily prayers, prophetic character, and essential Islamic ethics.',
  6
),
(
  7,
  'Ustadh Saad Ahmed',
  'Fiqh & Seerah Department Head',
  '/images/teacher_saad.png',
  'Arabic, English, Urdu',
  '10+ Years',
  'Fiqh, Seerah, Islamic History',
  'Graduate in Islamic Jurisprudence & Classical Arabic',
  'Ustadh Saad has dedicated over ten years to teaching Islamic history, the blessed life of Prophet Muhammad (PBUH), and practical day-to-day Fiqh rules. He is known for clear explanations that demystify complex questions.',
  7
),
(
  8,
  'Ustadha Maryam Zahra',
  'Youth & Kids Quran Specialist',
  '/images/teacher_maryam.png',
  'Arabic, English, Urdu',
  '7+ Years',
  'Islamic Studies, Noorani Qaida, Tajweed',
  'Certified Childhood Quran Pedagogy Educator',
  'Ustadha Maryam brings creativity and warmth to her online classroom. She uses interactive gamified learning, digital whiteboards, and positive reinforcement to help children build lifelong love for the Quran.',
  8
),
(
  9,
  'Ustadh Imran Qureshi',
  'Advanced Qira''at & Memorization Mentor',
  '/images/teacher_imran.jpg',
  'Arabic, English',
  '9+ Years',
  'Qur''an, Tajweed, Qira''at, Hifz',
  'Certified Hafiz with High Sanad (Isnad) in Recitation',
  'Ustadh Imran has mentored dozens of students to full Quran memorization. His structured revision milestones and deep understanding of recitation rules empower students to achieve excellence in both memorization and spiritual reflection.',
  9
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  avatar_url = EXCLUDED.avatar_url,
  languages = EXCLUDED.languages,
  experience = EXCLUDED.experience,
  specialization = EXCLUDED.specialization,
  education = EXCLUDED.education,
  bio = EXCLUDED.bio,
  order_index = EXCLUDED.order_index;

SELECT setval(pg_get_serial_sequence('public.teachers', 'id'), COALESCE(MAX(id), 1)) FROM public.teachers;
