-- ==========================================
-- SUPABASE DATABASE SCHEMAS FOR AERO WEBSITE
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. CONTACTS TABLE (Stores Contact Us form submissions)
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    ip_address TEXT,
    browser_info TEXT,
    system_info TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    provider TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration statement for existing table
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS browser_info TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS system_info TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS provider TEXT;

-- Enable Row Level Security (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (prevents clash errors on re-run)
DROP POLICY IF EXISTS "Allow public submissions" ON public.contacts;
DROP POLICY IF EXISTS "Allow authenticated read" ON public.contacts;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.contacts;

-- Enable Public inserts (allow anyone to submit the Contact form)
CREATE POLICY "Allow public submissions" ON public.contacts 
    FOR INSERT WITH CHECK (true);

-- Enable Admin reads/deletes (anyone with service role key, or customize for authenticated admins)
CREATE POLICY "Allow authenticated read" ON public.contacts
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated delete" ON public.contacts
    FOR DELETE USING (true);


-- 2. BLOGS TABLE (Stores blog articles and metadata)
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    read_time TEXT NOT NULL,
    author TEXT NOT NULL,
    featured_image TEXT,
    quote TEXT,
    quote_source TEXT,
    body TEXT NOT NULL,
    sections JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of { "title": "...", "content": "..." }
    second_quote TEXT,
    second_quote_source TEXT,
    seo_title TEXT,
    seo_description TEXT,
    seo_keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public select" ON public.blogs;
DROP POLICY IF EXISTS "Allow admin operations" ON public.blogs;

-- Enable Public selects (allow anyone to read blogs)
CREATE POLICY "Allow public select" ON public.blogs 
    FOR SELECT USING (true);

-- Enable Admin actions (inserts, updates, deletes)
CREATE POLICY "Allow admin operations" ON public.blogs
    FOR ALL USING (true);


-- 3. SEO SETTINGS TABLE (Stores page-specific and global SEO tags)
CREATE TABLE IF NOT EXISTS public.seo_settings (
    id TEXT PRIMARY KEY, -- e.g. 'global', 'home', 'blog'
    title TEXT NOT NULL,
    description TEXT,
    keywords TEXT,
    favicon_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.seo_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public SEO select" ON public.seo_settings;
DROP POLICY IF EXISTS "Allow admin SEO operations" ON public.seo_settings;

-- Enable Public select (allow public pages to fetch metadata)
CREATE POLICY "Allow public SEO select" ON public.seo_settings
    FOR SELECT USING (true);

-- Enable Admin edits
CREATE POLICY "Allow admin SEO operations" ON public.seo_settings
    FOR ALL USING (true);


-- ==========================================
-- SEED DATA (Default Admin data to start with)
-- ==========================================

-- Seed default global SEO settings
INSERT INTO public.seo_settings (id, title, description, keywords) VALUES
('global', 'Aero - Premium Next.js App', 'Deploy high-performance web applications with stunning visual aesthetics and sleek interactions.', 'nextjs, react, vanilla css, premium ui, glassmorphism')
ON CONFLICT (id) DO NOTHING;

-- Seed default blog matching your screenshot
INSERT INTO public.blogs (
    title, slug, category, read_time, author, featured_image, 
    quote, quote_source, body, sections, second_quote, second_quote_source,
    seo_title, seo_description, seo_keywords
) VALUES (
    'The Beauty of Tadabbur: Reflecting on the Quran',
    'beauty-of-tadabbur-reflecting-on-the-quran',
    'Quran & Tafsir',
    '5 min read',
    'Yaqeen Institute Team',
    'https://images.unsplash.com/photo-1609599006353-e629f1d40e39?auto=format&fit=crop&q=80&w=800',
    'Do they not then reflect on the Quran, or are there locks upon their hearts?',
    'Quran (47:24)',
    'Tadabbur is more than just reading the Quran — it is reflecting, pondering, and connecting with its meanings. When we take time to understand the words of Allah, the Quran transforms from a book we recite into a light that guides our hearts and lives.',
    '[
        {
            "title": "What is Tadabbur?",
            "content": "Tadabbur means to deeply contemplate the verses of the Quran and think about their meanings, lessons, and how they apply to our daily lives. Allah invites us to reflect so that we may gain understanding and grow in faith."
        },
        {
            "title": "Why is it Important?",
            "content": "When we practice Tadabbur, our connection with Allah becomes stronger. It helps us make better decisions, find comfort in difficult times, and live with purpose and clarity."
        },
        {
            "title": "How to Practice Tadabbur",
            "content": "Start by reading a verse slowly, look up its meaning, reflect on the lesson, and ask yourself how you can apply it. Make dua for understanding and consistency."
        }
    ]'::jsonb,
    'And We have certainly made the Quran easy for remembrance, so is there any who will remember?',
    'Quran (54:17)',
    'The Beauty of Tadabbur: Reflecting on the Quran | Aero Blog',
    'Understand what Tadabbur is, why it is important, and how to practice reflection on the Quran.',
    'Tadabbur, Quran, reflection, Yaqeen Institute'
) ON CONFLICT (slug) DO NOTHING;


-- ==========================================
-- 4. STORAGE BUCKET CREATION (For image uploads)
-- ==========================================

-- Create public storage bucket 'blog-images' if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('blog-images', 'blog-images', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing storage policies if they exist
DROP POLICY IF EXISTS "Allow public uploads to blog-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read from blog-images" ON storage.objects;

-- Enable public uploads (anonymous upload access)
CREATE POLICY "Allow public uploads to blog-images" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'blog-images');

-- Enable public read access
CREATE POLICY "Allow public read from blog-images" ON storage.objects
    FOR SELECT USING (bucket_id = 'blog-images');


-- ==========================================
-- 5. ADMIN PROFILE TABLE (Stores admin credentials, OTP, and session)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admin_profile (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    otp_code TEXT,
    otp_expires_at TIMESTAMP WITH TIME ZONE,
    session_token TEXT,
    session_expires_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.admin_profile ENABLE ROW LEVEL SECURITY;

-- Seed default admin credentials
INSERT INTO public.admin_profile (id, email, password)
VALUES ('admin', 'objectsquarerajan@gmail.com', 'admin123')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 6. SITE SETTINGS TABLE (Stores public logo text and logo image)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    id TEXT PRIMARY KEY DEFAULT 'global',
    logo_text TEXT DEFAULT 'yaqeen',
    logo_url TEXT,
    contact_email TEXT DEFAULT 'info@yaqeeninstitute.com',
    contact_phone TEXT DEFAULT '+447488818192',
    contact_hours TEXT DEFAULT '24x7 - We''re always here for you.',
    contact_support TEXT DEFAULT 'We serve students from around the world.',
    social_facebook TEXT DEFAULT '',
    social_instagram TEXT DEFAULT '',
    social_youtube TEXT DEFAULT '',
    social_whatsapp TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration statement to add columns to existing table
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_email TEXT DEFAULT 'info@yaqeeninstitute.com';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_phone TEXT DEFAULT '+447488818192';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_hours TEXT DEFAULT '24x7 - We''re always here for you.';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS contact_support TEXT DEFAULT 'We serve students from around the world.';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS social_facebook TEXT DEFAULT '';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS social_instagram TEXT DEFAULT '';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS social_youtube TEXT DEFAULT '';
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS social_whatsapp TEXT DEFAULT '';

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to logo configurations
DROP POLICY IF EXISTS "Allow public site settings read" ON public.site_settings;
CREATE POLICY "Allow public site settings read" ON public.site_settings
    FOR SELECT USING (true);

-- Allow admin full operations on site settings
DROP POLICY IF EXISTS "Allow admin site settings edits" ON public.site_settings;
CREATE POLICY "Allow admin site settings edits" ON public.site_settings
    FOR ALL USING (true);

-- Seed default logo text
INSERT INTO public.site_settings (id, logo_text)
VALUES ('global', 'yaqeen')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 7. LEADS TABLE (Stores Waitlist Leads / Newsletter signups)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Allow public insertions (anyone can submit email to newsletter/waitlist)
DROP POLICY IF EXISTS "Allow public inserts" ON public.leads;
CREATE POLICY "Allow public inserts" ON public.leads 
    FOR INSERT WITH CHECK (true);

-- Allow admin operations (reads/deletes)
DROP POLICY IF EXISTS "Allow admin operations on leads" ON public.leads;
CREATE POLICY "Allow admin operations on leads" ON public.leads
    FOR ALL USING (true);


-- ==========================================
-- 8. TEACHERS TABLE (Stores dynamic teacher profiles)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    avatar_url TEXT,
    languages TEXT NOT NULL,
    experience TEXT NOT NULL,
    specialization TEXT NOT NULL,
    bio TEXT,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration: add bio column to existing teachers tables (shown on Featured Teacher card)
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS bio TEXT;

-- Enable RLS
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Allow public teachers select" ON public.teachers;
CREATE POLICY "Allow public teachers select" ON public.teachers
    FOR SELECT USING (true);

-- Allow admin full operations
DROP POLICY IF EXISTS "Allow admin teachers operations" ON public.teachers;
CREATE POLICY "Allow admin teachers operations" ON public.teachers
    FOR ALL USING (true);

-- Seed default teachers data
INSERT INTO public.teachers (id, name, avatar_url, languages, experience, specialization, order_index) VALUES
(1, 'Ustadh Rahman Ali', '/images/teacher_rahman.png', 'Arabic, English, Urdu', '8+ Years', 'Qur''an, Tajweed', 1),
(2, 'Ustadha Aisha Khan', '/images/teacher_aisha.png', 'Arabic, English', '6+ Years', 'Tafseer, Hadith', 2),
(3, 'Ustadh Saad Ahmed', '/images/teacher_saad.png', 'Arabic, English, Urdu', '10+ Years', 'Fiqh, Seerah', 3),
(4, 'Ustadha Maryam Zahra', '/images/teacher_maryam.png', 'Arabic, English, Urdu', '7+ Years', 'Islamic Studies', 4)
ON CONFLICT (id) DO NOTHING;

-- Synchronize the primary key sequence (prevents duplicate key errors after manual inserts)
SELECT setval(pg_get_serial_sequence('public.teachers', 'id'), COALESCE(MAX(id), 1)) FROM public.teachers;


-- ==========================================
-- 9. TESTIMONIALS TABLE (Stores dynamic client testimonials)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    avatar_url TEXT,
    page_target TEXT DEFAULT 'all', -- 'all' or comma-separated pages like 'home,about'
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Allow public testimonials select" ON public.testimonials;
CREATE POLICY "Allow public testimonials select" ON public.testimonials
    FOR SELECT USING (true);

-- Allow admin full operations
DROP POLICY IF EXISTS "Allow admin testimonials operations" ON public.testimonials;
CREATE POLICY "Allow admin testimonials operations" ON public.testimonials
    FOR ALL USING (true);

-- Seed default testimonials data
INSERT INTO public.testimonials (id, name, role, content, avatar_url, page_target, order_index) VALUES
(1, 'Ayesha Khan', 'Mother of 2', 'Yaqeen has helped my child develop a strong understanding of Islam in a fun and meaningful way. Highly recommended!', '/images/testi_ayesha.png', 'all', 1),
(2, 'Hassan Ali', 'Adult Learner', 'The lessons are clear, engaging and practical. I appreciate how easy it is to stay consistent with my learning.', '/images/testi_hassan.png', 'all', 2),
(3, 'Maryam Zahra', 'Parent', 'We love how the whole family can learn together. Yaqeen has brought us closer to our faith and each other.', '/images/testi_maryam.png', 'all', 3)
ON CONFLICT (id) DO NOTHING;

-- Synchronize the primary key sequence
SELECT setval(pg_get_serial_sequence('public.testimonials', 'id'), COALESCE(MAX(id), 1)) FROM public.testimonials;


-- ==========================================
-- 10. COURSES TABLE (Stores dynamic courses list)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT,
    icon TEXT NOT NULL DEFAULT 'book', -- 'book', 'dad', 'mosque', 'badge', 'pencil'
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration: course detail page content fields (managed from admin Manage Courses)
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS level TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS class_duration TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS course_duration TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS mode TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS age_group TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS learn_points TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS who_for TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS content_details TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS course_modules TEXT;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS faqs TEXT;

-- Enable RLS
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Allow public courses select" ON public.courses;
CREATE POLICY "Allow public courses select" ON public.courses
    FOR SELECT USING (true);

-- Allow admin full operations
DROP POLICY IF EXISTS "Allow admin courses operations" ON public.courses;
CREATE POLICY "Allow admin courses operations" ON public.courses
    FOR ALL USING (true);

-- Seed default courses data
INSERT INTO public.courses (id, title, image_url, icon, order_index) VALUES
(1, 'Quran Learning with Tajweed', '/images/course_quran.png', 'book', 1),
(2, 'Arabic Language Mastery', '/images/course_arabic.png', 'dad', 2),
(3, 'Islamic Studies & Character Building', '/images/course_studies.png', 'mosque', 3),
(4, 'Quran Hifz Memorization', '/images/course_quran.png', 'badge', 4),
(5, 'Noorani Qaida for Beginners', '/images/course_arabic.png', 'pencil', 5),
(6, 'Tafseer & Quran Understanding', '/images/course_quran.png', 'book', 6)
ON CONFLICT (id) DO NOTHING;

-- Synchronize the primary key sequence
SELECT setval(pg_get_serial_sequence('public.courses', 'id'), COALESCE(MAX(id), 1)) FROM public.courses;


-- ==========================================
-- 11. PRICING PLANS TABLE (Stores dynamic plans)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subtitle TEXT,
    price TEXT NOT NULL,
    period TEXT DEFAULT '/hour',
    icon TEXT NOT NULL DEFAULT 'plane', -- 'plane', 'star', 'diamond', 'crown'
    badge TEXT, -- e.g. 'Best Value' or null
    features JSONB NOT NULL DEFAULT '[]'::jsonb, -- e.g. [{"text": "Proficient Arabic...", "included": true}]
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.pricing_plans ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Allow public pricing_plans select" ON public.pricing_plans;
CREATE POLICY "Allow public pricing_plans select" ON public.pricing_plans
    FOR SELECT USING (true);

-- Allow admin full operations
DROP POLICY IF EXISTS "Allow admin pricing_plans operations" ON public.pricing_plans;
CREATE POLICY "Allow admin pricing_plans operations" ON public.pricing_plans
    FOR ALL USING (true);

-- Seed default pricing plans data
INSERT INTO public.pricing_plans (id, name, subtitle, price, period, icon, badge, features, order_index) VALUES
(1, 'Basic', 'Entry Level Package', '8.00', '/hour', 'plane', NULL, '[
  {"text": "Proficient Arabic (Native) Teacher", "included": true},
  {"text": "E-Certificate", "included": true},
  {"text": "E-Syllabus Access", "included": true},
  {"text": "Direct Chat with Teacher and Coach", "included": true},
  {"text": "Lesson Reschedules", "included": false},
  {"text": "Coaching and Planning Sessions", "included": false},
  {"text": "Progress Report", "included": false},
  {"text": "Lesson Cancellation", "included": false},
  {"text": "Family Discount", "included": false},
  {"text": "Top 5 Star Rated Teacher", "included": false},
  {"text": "Video Recordings", "included": false}
]'::jsonb, 1),
(2, 'Essentials', 'Core Feature Set', '9.00', '/hour', 'star', NULL, '[
  {"text": "Proficient Arabic (Native) Teacher", "included": true},
  {"text": "E-Certificate", "included": true},
  {"text": "E-Syllabus Access", "included": true},
  {"text": "Direct Chat with Teacher and Coach", "included": true},
  {"text": "Up to 2 Lesson Reschedules per Month*", "included": true},
  {"text": "Coaching and Planning Sessions", "included": false},
  {"text": "Progress Report", "included": false},
  {"text": "Lesson Cancellation", "included": false},
  {"text": "Family Discounts", "included": false},
  {"text": "Top 5 Star Rated Teacher", "included": false},
  {"text": "Video Recordings", "included": false}
]'::jsonb, 2),
(3, 'Premium', 'Advanced Benefits', '11.00', '/hour', 'diamond', 'Best Value', '[
  {"text": "Proficient Arabic (Native) Teacher", "included": true},
  {"text": "E-Certificate", "included": true},
  {"text": "E-Syllabus Access", "included": true},
  {"text": "Direct Chat with Teacher and Coach", "included": true},
  {"text": "Up to 4 Lesson Reschedules per Month*", "included": true},
  {"text": "Coaching and Planning Sessions Twice a Year", "included": true},
  {"text": "Progress Report Twice a Year", "included": true},
  {"text": "Up to 1 Lesson Cancellation per Month**", "included": true},
  {"text": "5% Family Discounts***", "included": true},
  {"text": "Top 5 Star Rated Teacher", "included": false},
  {"text": "Video Recordings", "included": false}
]'::jsonb, 3),
(4, 'Platinum', 'Top-tier Access', '14.00', '/hour', 'crown', NULL, '[
  {"text": "Proficient Arabic (Native) Teacher", "included": true},
  {"text": "E-Certificate", "included": true},
  {"text": "E-Syllabus Access", "included": true},
  {"text": "Direct Chat with Teacher and Coach", "included": true},
  {"text": "Unlimited Reschedules per Month*", "included": true},
  {"text": "Coaching and Planning Sessions Every Quarter", "included": true},
  {"text": "Progress Report Every Quarter", "included": true},
  {"text": "Up to 3 Lesson Cancellations per Month**", "included": true},
  {"text": "10% Family Discounts***", "included": true},
  {"text": "Top 5 Star Rated Teacher", "included": true},
  {"text": "Video Recordings", "included": true}
]'::jsonb, 4)
ON CONFLICT (id) DO NOTHING;

-- Synchronize the primary key sequence
SELECT setval(pg_get_serial_sequence('public.pricing_plans', 'id'), COALESCE(MAX(id), 1)) FROM public.pricing_plans;



-- ==========================================
-- TEACHER APPLICATIONS TABLE
-- (Stores "Teacher Application" multi-step form submissions)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.teacher_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Step 1: Personal Information
    first_name TEXT,
    last_name TEXT,
    gender TEXT,
    email TEXT,
    dial_code TEXT,
    mobile TEXT,
    country TEXT,
    date_of_birth TEXT,
    nationality TEXT,
    occupation TEXT,
    marital_status TEXT,
    about_me TEXT,
    facebook TEXT,
    profile_image_url TEXT,
    -- Step 2: Academic & Professional
    education TEXT,
    years_experience TEXT,
    mother_language TEXT,
    other_language TEXT,
    cv_url TEXT,
    -- Step 3: Reading & Reciting
    reading_audio_url TEXT,
    recitation_audio_url TEXT,
    -- Step 4: Application details
    applying_for TEXT,
    has_ijazah TEXT,
    teach_tajweed_english TEXT,
    has_children TEXT,
    preferred_interview_time TEXT,
    expected_salary TEXT,
    hours_per_week TEXT,
    employment_type TEXT,
    ideal_candidate TEXT,
    how_found TEXT,
    declaration BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.teacher_applications ENABLE ROW LEVEL SECURITY;

-- Reset policies (safe re-run)
DROP POLICY IF EXISTS "Allow public teacher applications" ON public.teacher_applications;
DROP POLICY IF EXISTS "Allow read teacher applications" ON public.teacher_applications;
DROP POLICY IF EXISTS "Allow delete teacher applications" ON public.teacher_applications;

-- Public can submit; admin (anon/service) can read & delete (mirrors contacts table)
CREATE POLICY "Allow public teacher applications" ON public.teacher_applications
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow read teacher applications" ON public.teacher_applications
    FOR SELECT USING (true);
CREATE POLICY "Allow delete teacher applications" ON public.teacher_applications
    FOR DELETE USING (true);


-- ==========================================
-- CAREER JOBS TABLE (Stores Career page job openings, managed from admin)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.career_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    job_title TEXT,
    meta TEXT,
    badge TEXT DEFAULT 'Online',
    description TEXT,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.career_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public career_jobs select" ON public.career_jobs;
CREATE POLICY "Allow public career_jobs select" ON public.career_jobs
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin career_jobs operations" ON public.career_jobs;
CREATE POLICY "Allow admin career_jobs operations" ON public.career_jobs
    FOR ALL USING (true);

-- Seed default job openings
INSERT INTO public.career_jobs (id, title, job_title, meta, badge, description, order_index) VALUES
(1, 'Quran Teacher — Female', 'Quran Study with Tajweed & Makharij', 'Permanent | 2 Years Exp. | Bilingual (English/Arabic)', 'Online', 'Quran Teacher with Ijazah and 2–3 years of online teaching experience for all ages.', 1),
(2, 'Arabic Teacher — Female', 'Arabic Language Study', 'Permanent | 2 Years Exp. | Bilingual (English/Arabic)', 'Online', 'Arabic teacher with command of the Arabic language, able to design the course per age group and teach the school Arabic curriculum, with a minimum of 2–3 years of experience.', 2),
(3, 'Admin Staff — Female', 'Administrative Co-ordinator', 'Permanent | 2 Years Exp. | Bilingual (English/Arabic)', 'Online', 'Manage letters, communicate with clients and the public with excellent written communication. Must be well organised to keep the schedule of teachers and kids; minimum 2 years of experience.', 3),
(4, 'Digital Marketing Staff — Female', 'Digital Marketing Executive', 'Permanent | 2 Years Exp. | Bilingual (English/Arabic)', 'Online', 'Plans and implements display, email, social media and web advertising campaigns; evaluates and reports on digital marketing performance against objectives (ROI and KPIs).', 4)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.career_jobs', 'id'), COALESCE(MAX(id), 1)) FROM public.career_jobs;
 