-- ==========================================
-- SUPABASE DATABASE SCHEMAS FOR AERO WEBSITE
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. CONTACTS TABLE (Stores Contact Us form submissions)
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (prevents clash errors on re-run)
DROP POLICY IF EXISTS "Allow public submissions" ON public.contacts;
DROP POLICY IF EXISTS "Allow authenticated read" ON public.contacts;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.contacts;

-- Enable Public inserts (allow anyone to submit the Contact form)
CREATE POLICY "Allow public submissions" ON public.contacts 
    FOR INSERT WITH CHECK (true);

-- Enable Admin reads/deletes (anyone with service role key, or customize for authenticated admins)
CREATE POLICY "Allow authenticated read" ON public.contacts
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated delete" ON public.contacts
    FOR DELETE USING (true);


-- 2. BLOGS TABLE (Stores blog articles and metadata)
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    read_time TEXT NOT NULL,
    author TEXT NOT NULL,
    featured_image TEXT,
    quote TEXT,
    quote_source TEXT,
    body TEXT NOT NULL,
    sections JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of { "title": "...", "content": "..." }
    second_quote TEXT,
    second_quote_source TEXT,
    seo_title TEXT,
    seo_description TEXT,
    seo_keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public select" ON public.blogs;
DROP POLICY IF EXISTS "Allow admin operations" ON public.blogs;

-- Enable Public selects (allow anyone to read blogs)
CREATE POLICY "Allow public select" ON public.blogs 
    FOR SELECT USING (true);

-- Enable Admin actions (inserts, updates, deletes)
CREATE POLICY "Allow admin operations" ON public.blogs
    FOR ALL USING (true);


-- 3. SEO SETTINGS TABLE (Stores page-specific and global SEO tags)
CREATE TABLE IF NOT EXISTS public.seo_settings (
    id TEXT PRIMARY KEY, -- e.g. 'global', 'home', 'blog'
    title TEXT NOT NULL,
    description TEXT,
    keywords TEXT,
    favicon_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.seo_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public SEO select" ON public.seo_settings;
DROP POLICY IF EXISTS "Allow admin SEO operations" ON public.seo_settings;

-- Enable Public select (allow public pages to fetch metadata)
CREATE POLICY "Allow public SEO select" ON public.seo_settings
    FOR SELECT USING (true);

-- Enable Admin edits
CREATE POLICY "Allow admin SEO operations" ON public.seo_settings
    FOR ALL USING (true);


-- ==========================================
-- SEED DATA (Default Admin data to start with)
-- ==========================================

-- Seed default global SEO settings
INSERT INTO public.seo_settings (id, title, description, keywords) VALUES
('global', 'Aero - Premium Next.js App', 'Deploy high-performance web applications with stunning visual aesthetics and sleek interactions.', 'nextjs, react, vanilla css, premium ui, glassmorphism')
ON CONFLICT (id) DO NOTHING;

-- Seed default blog matching your screenshot
INSERT INTO public.blogs (
    title, slug, category, read_time, author, featured_image, 
    quote, quote_source, body, sections, second_quote, second_quote_source,
    seo_title, seo_description, seo_keywords
) VALUES (
    'The Beauty of Tadabbur: Reflecting on the Quran',
    'beauty-of-tadabbur-reflecting-on-the-quran',
    'Quran & Tafsir',
    '5 min read',
    'Yaqeen Institute Team',
    'https://images.unsplash.com/photo-1609599006353-e629f1d40e39?auto=format&fit=crop&q=80&w=800',
    'Do they not then reflect on the Quran, or are there locks upon their hearts?',
    'Quran (47:24)',
    'Tadabbur is more than just reading the Quran — it is reflecting, pondering, and connecting with its meanings. When we take time to understand the words of Allah, the Quran transforms from a book we recite into a light that guides our hearts and lives.',
    '[
        {
            "title": "What is Tadabbur?",
            "content": "Tadabbur means to deeply contemplate the verses of the Quran and think about their meanings, lessons, and how they apply to our daily lives. Allah invites us to reflect so that we may gain understanding and grow in faith."
        },
        {
            "title": "Why is it Important?",
            "content": "When we practice Tadabbur, our connection with Allah becomes stronger. It helps us make better decisions, find comfort in difficult times, and live with purpose and clarity."
        },
        {
            "title": "How to Practice Tadabbur",
            "content": "Start by reading a verse slowly, look up its meaning, reflect on the lesson, and ask yourself how you can apply it. Make dua for understanding and consistency."
        }
    ]'::jsonb,
    'And We have certainly made the Quran easy for remembrance, so is there any who will remember?',
    'Quran (54:17)',
    'The Beauty of Tadabbur: Reflecting on the Quran | Aero Blog',
    'Understand what Tadabbur is, why it is important, and how to practice reflection on the Quran.',
    'Tadabbur, Quran, reflection, Yaqeen Institute'
) ON CONFLICT (slug) DO NOTHING;


-- ==========================================
-- 4. STORAGE BUCKET CREATION (For image uploads)
-- ==========================================

-- Create public storage bucket 'blog-images' if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('blog-images', 'blog-images', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing storage policies if they exist
DROP POLICY IF EXISTS "Allow public uploads to blog-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read from blog-images" ON storage.objects;

-- Enable public uploads (anonymous upload access)
CREATE POLICY "Allow public uploads to blog-images" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'blog-images');

-- Enable public read access
CREATE POLICY "Allow public read from blog-images" ON storage.objects
    FOR SELECT USING (bucket_id = 'blog-images');


-- ==========================================
-- 5. ADMIN PROFILE TABLE (Stores admin credentials, OTP, and session)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admin_profile (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    otp_code TEXT,
    otp_expires_at TIMESTAMP WITH TIME ZONE,
    session_token TEXT,
    session_expires_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.admin_profile ENABLE ROW LEVEL SECURITY;

-- Seed default admin credentials
INSERT INTO public.admin_profile (id, email, password)
VALUES ('admin', 'objectsquarerajan@gmail.com', 'admin123')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 6. SITE SETTINGS TABLE (Stores public logo text and logo image)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    id TEXT PRIMARY KEY DEFAULT 'global',
    logo_text TEXT DEFAULT 'yaqeen',
    logo_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to logo configurations
DROP POLICY IF EXISTS "Allow public site settings read" ON public.site_settings;
CREATE POLICY "Allow public site settings read" ON public.site_settings
    FOR SELECT USING (true);

-- Allow admin full operations on site settings
DROP POLICY IF EXISTS "Allow admin site settings edits" ON public.site_settings;
CREATE POLICY "Allow admin site settings edits" ON public.site_settings
    FOR ALL USING (true);

-- Seed default logo text
INSERT INTO public.site_settings (id, logo_text)
VALUES ('global', 'yaqeen')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 7. LEADS TABLE (Stores Waitlist Leads / Newsletter signups)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Allow public insertions (anyone can submit email to newsletter/waitlist)
DROP POLICY IF EXISTS "Allow public inserts" ON public.leads;
CREATE POLICY "Allow public inserts" ON public.leads 
    FOR INSERT WITH CHECK (true);

-- Allow admin operations (reads/deletes)
DROP POLICY IF EXISTS "Allow admin operations on leads" ON public.leads;
CREATE POLICY "Allow admin operations on leads" ON public.leads
    FOR ALL USING (true);
