export const ALL_TEACHERS = [
  {
    id: 1,
    slug: "mazin-yasir",
    name: "Ustadh Mazin Yasir",
    title: "Senior Quran & Tajweed Specialist",
    headline: "Online Quran & Arabic Teacher",
    avatar_url: "/images/teacher_mazin.jpg",
    gender: "male",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "3+ Years",
    specialization: "Qur'an, Tajweed, Islamic Studies",
    education_title: "Degree in Islamic Studies & Quranic Sciences",
    education_sub: "Al-Azhar University — Graduation",
    education: "Degree in Islamic Studies & Quranic Sciences • Ijazah in Hafs 'an 'Asim",
    quote: "I strive to make Quran recitation intuitive, correcting pronunciation with patience and helping every student find peace in the words of Allah.",
    short_bio: "Ustadh Mazin is a dedicated and experienced teacher who is passionate about helping students learn the Quran and Arabic confidently. He creates engaging and supportive lessons that make learning enjoyable and effective.",
    long_bio: "Ustadh Mazin Yasir is an Azhar-trained Quran instructor specializing in foundational Tajweed, correct articulation points (Makharij), and melodic recitation. With years of experience guiding beginner and intermediate students worldwide, his patient and structured approach helps students cultivate lasting confidence and love for the Holy Quran.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "He designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "With a Degree in Islamic Studies & Quranic Sciences from Al-Azhar University, Ustadh Mazin brings a solid foundation in Islamic knowledge, supporting students with authentic and reliable guidance."
  },
  {
    id: 2,
    slug: "naira-tarek",
    name: "Ustadha Naira Tarek",
    title: "Arabic Language & Quran Instructor",
    headline: "Online Quran & Arabic Teacher",
    avatar_url: "/images/teacher_naira.jpg",
    gender: "female",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "4+ Years",
    specialization: "Qur'an, Arabic Language, Islamic Studies",
    education_title: "Bachelor of Arts in Arabic Linguistics",
    education_sub: "Cairo University — Classical Grammar",
    education: "Bachelor of Arts in Arabic Linguistics & Classical Quranic Grammar",
    quote: "Language is the key to understanding the Quran. I empower my students to speak, read, and connect with Arabic with joy and ease.",
    short_bio: "Ustadha Naira is an engaging and passionate Arabic & Quran tutor who helps female students and young children build strong language foundations and fluent recitation in an encouraging environment.",
    long_bio: "Ustadha Naira Tarek has trained hundreds of young learners and female students across the globe. She blends classical Arabic grammar with lively conversational practice and gentle Tajweed correction, creating an encouraging classroom where students flourish naturally.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "She designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "With a Bachelor's Degree in Arabic Linguistics and classical grammar, Ustadha Naira brings deep linguistic mastery and authentic pedagogical techniques to every session."
  },
  {
    id: 3,
    slug: "muhammad-sabry",
    name: "Muhammad Sabry",
    title: "Azhari Scholar & Hifz Coach",
    headline: "Online Quran & Arabic Teacher",
    avatar_url: "/images/teacher_sabry.jpg",
    gender: "male",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "5+ Years",
    specialization: "Quran, Arabic Language, Islamic Studies",
    education_title: "Bachelor's Degree in Islamic",
    education_sub: "Da'wah Studies\nAl-Azhar University — Graduation",
    education: "Bachelor's Degree in Islamic Da'wah Studies • Al-Azhar University — Graduation",
    quote: "I enjoy helping my students build a strong connection with the Quran and Arabic and gain confidence in their learning journey.",
    short_bio: "Muhammad Sabry is a dedicated and experienced teacher who is passionate about helping students learn the Quran and Arabic confidently. He creates engaging and supportive lessons that make learning enjoyable and effective.",
    long_bio: "Muhammad Sabry is a native Arabic speaker with several years of experience in online Quran and Arabic teaching. He is passionate about helping students of all ages develop strong recitation, Arabic language skills, and a deeper connection with Islamic knowledge through engaging and structured lessons.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "He designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "With a Bachelor's Degree in Islamic Da'wah Studies from Al-Azhar University, Muhammad Sabry brings a solid foundation in Islamic knowledge, supporting students with authentic and reliable guidance."
  },
  {
    id: 4,
    slug: "amira-attaf",
    name: "Ustadha Amira Attaf",
    title: "Senior Tafseer & Islamic Studies Teacher",
    headline: "Online Quran & Tafseer Specialist",
    avatar_url: "/images/teacher_amira.jpg",
    gender: "female",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "10+ Years",
    specialization: "Qur'an, Tajweed, Tafseer, Islamic Studies",
    education_title: "Master's Degree in Islamic Studies",
    education_sub: "Certified Tajweed Educator — Al-Azhar",
    education: "Master's in Islamic Studies • Certified Tajweed Educator",
    quote: "Understanding the meaning of the verses changes how we pray and live. I teach with heart-centered focus and clarity.",
    short_bio: "Ustadha Amira has over a decade of teaching experience guiding sisters and children in Quranic reflection, spiritual growth, and deep Tajweed mastery.",
    long_bio: "With over a decade of teaching experience across the UK and Middle East, Ustadha Amira is renowned for her profound knowledge of Quranic Tafseer and spiritual development. She tailors every class to each student's individual pace, ensuring both intellectual clarity and heart-centered learning.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "She designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "Holding a Master's degree in Islamic Studies and high certification in Tajweed, Ustadha Amira provides deep spiritual insight and academic rigor."
  },
  {
    id: 5,
    slug: "rahman-ali",
    name: "Ustadh Rahman Ali",
    title: "Lead Recitation & Makharij Coach",
    headline: "Online Quran & Tajweed Specialist",
    avatar_url: "/images/teacher_rahman.png",
    gender: "male",
    country: "Egypt",
    languages: "Arabic, English, Urdu",
    experience: "8+ Years",
    specialization: "Qur'an, Tajweed, Noorani Qaida",
    education_title: "Certified Qari & Ijazah Holder",
    education_sub: "Ten Minor Qira'at — Faculty of Quran",
    education: "Certified Qari • Ijazah in Ten Minor Qira'at",
    quote: "Every student learns at their own pace. With gentle guidance and steady rhythm, Quran recitation becomes natural and inspiring.",
    short_bio: "Ustadh Rahman specializes in foundational Noorani Qaida for beginners and advanced melodic Tajweed for intermediate and advanced students.",
    long_bio: "Ustadh Rahman specializes in foundational Noorani Qaida for young beginners and advanced Tajweed melody and rhythm for older students. His patient demeanor makes learning smooth and enjoyable for all age groups.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "He designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "As a certified Qari with Ijazah in the Ten Minor Qira'at, Ustadh Rahman brings authoritative recitation standards to every lesson."
  },
  {
    id: 6,
    slug: "aisha-khan",
    name: "Ustadha Aisha Khan",
    title: "Hadith & Islamic Manners Instructor",
    headline: "Online Islamic Studies & Quran Teacher",
    avatar_url: "/images/teacher_aisha.png",
    gender: "female",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "6+ Years",
    specialization: "Tafseer, Hadith, Akhlaaq",
    education_title: "Alimiyyah Degree in Islamic Theology",
    education_sub: "Hadith Studies & Prophetic Ethics",
    education: "Alimiyyah Degree in Islamic Theology and Hadith Studies",
    quote: "Imparting prophetic character and daily Sunnah morals helps young Muslims flourish both spiritually and academically.",
    short_bio: "Ustadha Aisha focuses on bringing prophetic traditions (Sunnah) to life for modern Muslim families with warmth, clarity, and practical examples.",
    long_bio: "Ustadha Aisha focuses on bringing the prophetic traditions (Sunnah) to life for modern Muslim families. She guides students in understanding daily prayers, prophetic character, and essential Islamic ethics.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "She designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "With an Alimiyyah degree in Islamic Theology and Hadith studies, Ustadha Aisha provides reliable, authentic guidance for the whole family."
  },
  {
    id: 7,
    slug: "saad-ahmed",
    name: "Ustadh Saad Ahmed",
    title: "Fiqh & Seerah Department Head",
    headline: "Online Islamic History & Fiqh Teacher",
    avatar_url: "/images/teacher_saad.png",
    gender: "male",
    country: "Egypt",
    languages: "Arabic, English, Urdu",
    experience: "10+ Years",
    specialization: "Fiqh, Seerah, Islamic History",
    education_title: "Graduate in Islamic Jurisprudence",
    education_sub: "Classical Arabic — Al-Azhar University",
    education: "Graduate in Islamic Jurisprudence & Classical Arabic",
    quote: "Exploring the life of the Prophet (PBUH) gives students practical blueprints for moral excellence in the modern world.",
    short_bio: "Ustadh Saad has dedicated over ten years to teaching Islamic history, the blessed Seerah of Prophet Muhammad (PBUH), and practical daily Fiqh.",
    long_bio: "Ustadh Saad has dedicated over ten years to teaching Islamic history, the blessed life of Prophet Muhammad (PBUH), and practical day-to-day Fiqh rules. He is known for clear explanations that demystify complex questions.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "He designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "Trained in classical Islamic Jurisprudence and Arabic at Al-Azhar, Ustadh Saad offers deep scholarly depth with accessible modern delivery."
  },
  {
    id: 8,
    slug: "maryam-zahra",
    name: "Ustadha Maryam Zahra",
    title: "Youth & Kids Quran Specialist",
    headline: "Online Quran & Noorani Qaida Teacher",
    avatar_url: "/images/teacher_maryam.png",
    gender: "female",
    country: "Egypt",
    languages: "Arabic, English, Urdu",
    experience: "7+ Years",
    specialization: "Islamic Studies, Noorani Qaida, Tajweed",
    education_title: "Certified Childhood Quran Pedagogy",
    education_sub: "Early Islamic Education Specialist",
    education: "Certified Childhood Quran Pedagogy Educator",
    quote: "Building a lifelong love for the Quran in children begins with kindness, fun interactive methods, and constant encouragement.",
    short_bio: "Ustadha Maryam brings creativity and warmth to her online classroom, utilizing digital whiteboards and gamified lessons to captivate young minds.",
    long_bio: "Ustadha Maryam brings creativity and warmth to her online classroom. She uses interactive gamified learning, digital whiteboards, and positive reinforcement to help children build lifelong love for the Quran.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "She designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "Certified in Early Childhood Quran Pedagogy, Ustadha Maryam applies proven methods to make learning rewarding and joyous."
  },
  {
    id: 9,
    slug: "imran-qureshi",
    name: "Ustadh Imran Qureshi",
    title: "Advanced Qira'at & Memorization Mentor",
    headline: "Online Quran Hifz & Qira'at Mentor",
    avatar_url: "/images/teacher_imran.jpg",
    gender: "male",
    country: "Egypt",
    languages: "Arabic, English",
    experience: "9+ Years",
    specialization: "Qur'an, Tajweed, Qira'at, Hifz",
    education_title: "Certified Hafiz with High Sanad",
    education_sub: "Isnad in Quranic Recitation",
    education: "Certified Hafiz with High Sanad (Isnad) in Recitation",
    quote: "Memorizing the Book of Allah is a sacred journey. Structured milestones and consistent review guarantee lifelong retention.",
    short_bio: "Ustadh Imran has mentored dozens of students to complete memorization of the Holy Quran with high precision and spiritual focus.",
    long_bio: "Ustadh Imran has mentored dozens of students to full Quran memorization. His structured revision milestones and deep understanding of recitation rules empower students to achieve excellence in both memorization and spiritual reflection.",
    approach_title: "Student-Centered Learning Approach",
    approach_desc: "He designs interactive and personalized lessons based on each student's level and learning goals, making Quran and Arabic learning simple, enjoyable, and effective.",
    academic_title: "Strong Academic Background",
    academic_desc: "Holding high Sanad in Quranic recitation, Ustadh Imran trains aspiring Huffaz with rigorous yet motivating memorization strategies."
  }
];

export function getTeacherByIdOrSlug(identifier) {
  if (!identifier) return ALL_TEACHERS[2]; // Default to Muhammad Sabry (ID: 3)
  const str = String(identifier).toLowerCase().trim();
  
  // Try match by ID
  const byId = ALL_TEACHERS.find(t => String(t.id) === str);
  if (byId) return byId;

  // Try match by slug
  const bySlug = ALL_TEACHERS.find(t => t.slug.toLowerCase() === str);
  if (bySlug) return bySlug;

  // Try match by name substring
  const byName = ALL_TEACHERS.find(t => t.name.toLowerCase().includes(str) || str.includes(t.slug));
  if (byName) return byName;

  return ALL_TEACHERS[2]; // Fallback to Muhammad Sabry
}
